### ISSUE TITLE
Improvement: Fix link to GitHub on Website

### ISSUE THREAD

**Issue by michue** [scratux-revived/scratux-revived.github.io#1]
Hey,

thank you for keeping this project alive!
While browsing your version, I stumbled across a wrong link on your website:

The banner in the top right is still pointing to the [original page](https://github.com/scratux/scratux), but not to your [fork](https://github.com/scratux-revived/scratux).

Corresponding code line:
https://github.com/scratux-revived/scratux-revived.github.io/blob/c5b292274506cc83073cb76e9d5d29df0d75df44/index.html#LL70C83-L70C83

**Comment by techguy16** [comment]
Hi,
Sorry for the late reply (like really late). I completely forgot about this project. Thanks for your contributions. I'll try to publish a new version soon. :)

**Comment by michue** [comment]
Don't worry, it wasn't that important :D
But I try to contribute to all open-source projects as soon as I see something, that can be fixed quite easily. This is, what keeps those projects alive :)
